steps:

- id: "Teste unitário"
  name: 'gcr.io/cloud-builders/go'
  args: ['test', './src/sum']

- id: "Criar imagem"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/fullcycle-desafio-ci:latest', '.']

- id: "Push imagem"
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/fullcycle-desafio-ci:latest']


- id: "Executar imagem criada"
  name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'gcr.io/$PROJECT_ID/fullcycle-desafio-ci:latest']

images:
- 'gcr.io/$PROJECT_ID/fullcycle-desafio-ci:latest'